### ISSUE TITLE
Plugin Fails to Load

### ISSUE THREAD

**Issue by smashedr** [Epix37/HDT-TwitchPlugin#8]
Seeing this in the logs when enabling the plugin:

```
5:48:53 PM|Info|PluginWrapper.Load >> Loading TwitchPlugin
5:48:53 PM|Info|ErrorManager.AddError >> New error: Error loading Plugin "TwitchPlugin"
Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
5:48:53 PM|Error|PluginWrapper.Load >> TwitchPlugin:
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
5:48:53 PM|Info|PluginWrapper.IsEnabled >> Enabled TwitchPlugin
```

**Comment by itSFox** [comment]
Same bug, and i really sad about it:
` 

```
8:46:04

 PM|Info|PluginWrapper.Load >> Loading TwitchPlugin
8:46:04 PM|Info|ErrorManager.AddError >> New error: Error loading Plugin "TwitchPlugin"
Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
8:46:04 PM|Error|PluginWrapper.Load >> TwitchPlugin:
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
8:46:04 PM|Info|PluginWrapper.IsEnabled >> Enabled TwitchPlugin 
```

**Comment by ghost** [comment]
https://gyazo.com/31aefdbac04b109697ddf9de2fb49d6f

I have the same problem.

**Comment by azeier** [comment]
The plugin is out of date. Not sure when I get around to fixing it, sorry guys. 

I'll try to get it working again some time soon.

**Comment by azeier** [comment]
New version is now available: https://github.com/azeier/HDT-TwitchPlugin/releases/tag/v0.6

**Comment by ghost** [comment]
The links for the decks are not working:

http://hss.io/d/13747506

I got this link on the twitch chat when typing: !alldecks but the link is not correct.

**Comment by ghost** [comment]
Actually I think Hearthstats its down. So it may not be your problem

**Comment by azeier** [comment]
HearthStats is no longer maintained. We are working on replacing it's functionality as soon as possible.
